// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Clipboard from 'stimulus-clipboard'

import AnswersController from "./answers_controller"
application.register("answers", AnswersController)

import DefaultQuizSessionController from "./default_quiz_session_controller"
application.register("default-quiz-session", DefaultQuizSessionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageController from "./image_controller"
application.register("image", ImageController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)

application.register('clipboard', Clipboard)
